/*
 * generated by Xtext 2.14.0
 */
package open.caesar.oml2.ide

import com.google.inject.Guice
import open.caesar.oml2.Oml2RuntimeModule
import open.caesar.oml2.Oml2StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Oml2IdeSetup extends Oml2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Oml2RuntimeModule, new Oml2IdeModule))
	}
	
}
