/*
 * generated by Xtext 2.14.0
 */
package open.caesar.oml.tests

import com.google.inject.Inject
import open.caesar.oml.Extent
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(OmlInjectorProvider)
class OmlParsingTest {
	@Inject
	ParseHelper<Extent> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			terminology T
			{
				concept c
				aspect  a
				relation r
				{
					source = c
					target = a
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
