/*
 * generated by Xtext 2.14.0
 */
package open.caesar.oml.ide

import com.google.inject.Guice
import open.caesar.oml.OmlRuntimeModule
import open.caesar.oml.OmlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OmlIdeSetup extends OmlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OmlRuntimeModule, new OmlIdeModule))
	}
	
}
