grammar open.caesar.oml.Oml with org.eclipse.xtext.common.Terminals

import "http://open.caesar/oml/Oml" 

Extent:
	modules+=Module*;
	
Module:
	Terminology;

Terminology: 
	'terminology' iri=ID
	'{'
		statements+=TerminologyStatement*
	'}';

TerminologyStatement:
	Term;
	
Term:
	Entity;
	
Entity:
	Aspect |
	Concept |
	Relation;

Aspect:
	'aspect' name=ID;

Concept:
	'concept' name=ID;

Relation:
	'relation' name=ID 
	'{' 
		'source' '=' source=[Entity]
		'target' '=' target=[Entity]
	'}';